spring:
  application:
    name: blogServer
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_server
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    dbcp2:
      auto-commit-on-return: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
